eureka:
  client:
    service-url:
      defaultZone: http://47.101.210.56:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 9411
spring:
  application:
    name: zipkinservice
#  sleuth:
#   sampler:
#      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  zipkin:
    rabbitmq:
      queue: zipkin
