zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    userdataservice:
      path: /dataapi/**
      serviceId: userdataservice
      sensitiveHeaders:
    usermanagement:
      path: /userapi/**
      serviceId: usermanagement
      sensitiveHeaders:
server:
  port: 5000
spring:
  application:
    name: gatewayservice
eureka:
  client:
    service-url:
      defaultZone: http://47.101.210.56:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}