server:
  port: 5001
spring:
  application:
    name: adminservice
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,hystrex.stream
      turbine:
        clusters: default
        location: turbinservice
eureka:
  client:
    service-url:
      defaultZone: http://47.101.210.56:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
management:
  security:
    enabled: false
