server:
  port: 9082
spring:
  application:
    name: userdataservice
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 47.101.210.56
    port: 5672
    username: admin
    password: admin
  zipkin:
    rabbitmq:
      queue: zipkin
  datasource:
    url: jdbc:mysql://cdb-fzbglzwr.gz.tencentcdb.com:10076/graduation
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://47.101.210.56:8761/eureka/
#用IP地址注册到erueka上
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#mybatis配置
mybatis:
  type-aliases-package: com.better517na.userdataservice.model       #映射model的地址
  mapper-locations: classpath:mapping/*.xml                         #对应mapping地址
logging:
  level: info
