server:
  port: 9082
spring:
  application:
    name: userdataservice
  datasource:
    url: jdbc:mysql://cdb-fzbglzwr.gz.tencentcdb.com:10076/graduation
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      #defaultZone: http://eureka2:8000/eureka/
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://47.101.210.56:8761/eureka/eureka/
#用IP地址注册到erueka上
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#mabatis配置
mybatis:
  type-aliases-package: com.better517na.userdataservice.model       #映射model的地址
  mapper-locations: classpath:mapping/*.xml                         #对应mapping地址