server:
  port: 8801
spring:
  application:
    name: usermanagement
#  zipkin:
#    base-url: http://localhost:9411/zipkin/
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 47.101.210.56
    port: 5672
    username: admin
    password: admin
  zipkin:
    rabbitmq:
      queue: zipkin
eureka:
  client:
    service-url:
      defaultZone: http://47.101.210.56:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
ribbon:
  eager-load:
    enabled: true
    clients: client1,client2