server:
  port: 8801
spring:
  application:
    name: usermanagementservice
eureka:
  client:
    service-url:
      defaultZone: http://47.101.210.56:8761/eureka/eureka/
      #defaultZone: http://eureka2:8000/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
